# Generated by Django 5.2.3 on 2025-06-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Genêros',
                'db_table': 'generos',
            },
        ),
    ]
